# This CI configuration is used for landing page deployment in external GitHub
# instances.
---
name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

permissions:
  contents: write

env:
  TRANSLATION_BRANCH: onion-launchpad
  ONION_LAUNCHPAD_SET_SAFE_DIRECTORY: 1
  LEKTOR_FOREGROUND_COLOR: ${{ secrets.LEKTOR_FOREGROUND_COLOR }}
  LEKTOR_BACKGROUND_COLOR: ${{ secrets.LEKTOR_BACKGROUND_COLOR }}
  LEKTOR_BUTTON_COLOR: ${{ secrets.LEKTOR_BUTTON_COLOR }}
  LEKTOR_ONION_URL_LOCK_FILTER: ${{ secrets.LEKTOR_ONION_URL_LOCK_FILTER }}
  LEKTOR_ONION_URL: ${{ secrets.LEKTOR_ONION_URL }}
  LEKTOR_SERVICE_NAME: ${{ secrets.LEKTOR_SERVICE_NAME }}
  LEKTOR_SERVICE_URL: ${{ secrets.LEKTOR_SERVICE_URL }}
  LEKTOR_FAVICON: ${{ secrets.LEKTOR_FAVICON }}
  LEKTOR_LOGO_PATH: ${{ secrets.LEKTOR_LOGO_PATH }}
  LEKTOR_ASSET_REPOSITORY_URL: ${{ secrets.LEKTOR_ASSET_REPOSITORY_URL }}
  LEKTOR_DEFAULT_LANGUAGE: ${{ secrets.LEKTOR_DEFAULT_LANGUAGE }}
  LEKTOR_AVAILABLE_LANGUAGES: ${{ secrets.LEKTOR_AVAILABLE_LANGUAGES }}
  LEKTOR_ANALYTICS: ${{ secrets.LEKTOR_ANALYTICS }}
  LEKTOR_ANALYTICS_SDK: ${{ secrets.LEKTOR_ANALYTICS_SDK }}
  LEKTOR_ANALYTICS_BACKEND: ${{ secrets.LEKTOR_ANALYTICS_BACKEND }}
  LEKTOR_ANALYTICS_SITE_ID: ${{ secrets.LEKTOR_ANALYTICS_SITE_ID }}
  LEKTOR_ANALYTICS_LINK_TRACKING: ${{ secrets.LEKTOR_ANALYTICS_LINK_TRACKING }}
  LEKTOR_ANALYTICS_BROWSER_DETECTION: ${{ secrets.LEKTOR_ANALYTICS_BROWSER_DETECTION }}
  LEKTOR_ANALYTICS_PRIVACY_POLICY_CONTACT: ${{ secrets.LEKTOR_ANALYTICS_PRIVACY_POLICY_CONTACT }}
  LEKTOR_ANALYTICS_BACKGROUND_COLOR: ${{ secrets.LEKTOR_ANALYTICS_BACKGROUND_COLOR }}
  LEKTOR_SERVICE_NAME_AM: ${{ secrets.LEKTOR_SERVICE_NAME_AM }}
  LEKTOR_SERVICE_NAME_AR: ${{ secrets.LEKTOR_SERVICE_NAME_AR }}
  LEKTOR_SERVICE_NAME_AZ: ${{ secrets.LEKTOR_SERVICE_NAME_AZ }}
  LEKTOR_SERVICE_NAME_BA: ${{ secrets.LEKTOR_SERVICE_NAME_BA }}
  LEKTOR_SERVICE_NAME_BE: ${{ secrets.LEKTOR_SERVICE_NAME_BE }}
  LEKTOR_SERVICE_NAME_BG: ${{ secrets.LEKTOR_SERVICE_NAME_BG }}
  LEKTOR_SERVICE_NAME_BN: ${{ secrets.LEKTOR_SERVICE_NAME_BN }}
  LEKTOR_SERVICE_NAME_BO: ${{ secrets.LEKTOR_SERVICE_NAME_BO }}
  LEKTOR_SERVICE_NAME_BS: ${{ secrets.LEKTOR_SERVICE_NAME_BS }}
  LEKTOR_SERVICE_NAME_CE: ${{ secrets.LEKTOR_SERVICE_NAME_CE }}
  LEKTOR_SERVICE_NAME_CKB: ${{ secrets.LEKTOR_SERVICE_NAME_CKB }}
  LEKTOR_SERVICE_NAME_CRH: ${{ secrets.LEKTOR_SERVICE_NAME_CRH }}
  LEKTOR_SERVICE_NAME_EN: ${{ secrets.LEKTOR_SERVICE_NAME_EN }}
  LEKTOR_SERVICE_NAME_ES: ${{ secrets.LEKTOR_SERVICE_NAME_ES }}
  LEKTOR_SERVICE_NAME_FA_AF: ${{ secrets.LEKTOR_SERVICE_NAME_FA_AF }}
  LEKTOR_SERVICE_NAME_FA: ${{ secrets.LEKTOR_SERVICE_NAME_FA }}
  LEKTOR_SERVICE_NAME_FR: ${{ secrets.LEKTOR_SERVICE_NAME_FR }}
  LEKTOR_SERVICE_NAME_HA: ${{ secrets.LEKTOR_SERVICE_NAME_HA }}
  LEKTOR_SERVICE_NAME_HE: ${{ secrets.LEKTOR_SERVICE_NAME_HE }}
  LEKTOR_SERVICE_NAME_HT: ${{ secrets.LEKTOR_SERVICE_NAME_HT }}
  LEKTOR_SERVICE_NAME_HU: ${{ secrets.LEKTOR_SERVICE_NAME_HU }}
  LEKTOR_SERVICE_NAME_HY: ${{ secrets.LEKTOR_SERVICE_NAME_HY }}
  LEKTOR_SERVICE_NAME_ID: ${{ secrets.LEKTOR_SERVICE_NAME_ID }}
  LEKTOR_SERVICE_NAME_IT: ${{ secrets.LEKTOR_SERVICE_NAME_IT }}
  LEKTOR_SERVICE_NAME_KA: ${{ secrets.LEKTOR_SERVICE_NAME_KA }}
  LEKTOR_SERVICE_NAME_KK: ${{ secrets.LEKTOR_SERVICE_NAME_KK }}
  LEKTOR_SERVICE_NAME_KM: ${{ secrets.LEKTOR_SERVICE_NAME_KM }}
  LEKTOR_SERVICE_NAME_KMR: ${{ secrets.LEKTOR_SERVICE_NAME_KMR }}
  LEKTOR_SERVICE_NAME_KO: ${{ secrets.LEKTOR_SERVICE_NAME_KO }}
  LEKTOR_SERVICE_NAME_KY: ${{ secrets.LEKTOR_SERVICE_NAME_KY }}
  LEKTOR_SERVICE_NAME_LN: ${{ secrets.LEKTOR_SERVICE_NAME_LN }}
  LEKTOR_SERVICE_NAME_LO: ${{ secrets.LEKTOR_SERVICE_NAME_LO }}
  LEKTOR_SERVICE_NAME_MK: ${{ secrets.LEKTOR_SERVICE_NAME_MK }}
  LEKTOR_SERVICE_NAME_MY: ${{ secrets.LEKTOR_SERVICE_NAME_MY }}
  LEKTOR_SERVICE_NAME_ND: ${{ secrets.LEKTOR_SERVICE_NAME_ND }}
  LEKTOR_SERVICE_NAME_OM: ${{ secrets.LEKTOR_SERVICE_NAME_OM }}
  LEKTOR_SERVICE_NAME_PS: ${{ secrets.LEKTOR_SERVICE_NAME_PS }}
  LEKTOR_SERVICE_NAME_PT_PT: ${{ secrets.LEKTOR_SERVICE_NAME_PT_PT }}
  LEKTOR_SERVICE_NAME_RN: ${{ secrets.LEKTOR_SERVICE_NAME_RN }}
  LEKTOR_SERVICE_NAME_RO: ${{ secrets.LEKTOR_SERVICE_NAME_RO }}
  LEKTOR_SERVICE_NAME_RU: ${{ secrets.LEKTOR_SERVICE_NAME_RU }}
  LEKTOR_SERVICE_NAME_RW: ${{ secrets.LEKTOR_SERVICE_NAME_RW }}
  LEKTOR_SERVICE_NAME_SG: ${{ secrets.LEKTOR_SERVICE_NAME_SG }}
  LEKTOR_SERVICE_NAME_SH: ${{ secrets.LEKTOR_SERVICE_NAME_SH }}
  LEKTOR_SERVICE_NAME_SO: ${{ secrets.LEKTOR_SERVICE_NAME_SO }}
  LEKTOR_SERVICE_NAME_SQ: ${{ secrets.LEKTOR_SERVICE_NAME_SQ }}
  LEKTOR_SERVICE_NAME_SR: ${{ secrets.LEKTOR_SERVICE_NAME_SR }}
  LEKTOR_SERVICE_NAME_SW: ${{ secrets.LEKTOR_SERVICE_NAME_SW }}
  LEKTOR_SERVICE_NAME_TG: ${{ secrets.LEKTOR_SERVICE_NAME_TG }}
  LEKTOR_SERVICE_NAME_TH: ${{ secrets.LEKTOR_SERVICE_NAME_TH }}
  LEKTOR_SERVICE_NAME_TI: ${{ secrets.LEKTOR_SERVICE_NAME_TI }}
  LEKTOR_SERVICE_NAME_TK: ${{ secrets.LEKTOR_SERVICE_NAME_TK }}
  LEKTOR_SERVICE_NAME_TR: ${{ secrets.LEKTOR_SERVICE_NAME_TR }}
  LEKTOR_SERVICE_NAME_TT: ${{ secrets.LEKTOR_SERVICE_NAME_TT }}
  LEKTOR_SERVICE_NAME_UG: ${{ secrets.LEKTOR_SERVICE_NAME_UG }}
  LEKTOR_SERVICE_NAME_UK: ${{ secrets.LEKTOR_SERVICE_NAME_UK }}
  LEKTOR_SERVICE_NAME_UR: ${{ secrets.LEKTOR_SERVICE_NAME_UR }}
  LEKTOR_SERVICE_NAME_UZ: ${{ secrets.LEKTOR_SERVICE_NAME_UZ }}
  LEKTOR_SERVICE_NAME_VI: ${{ secrets.LEKTOR_SERVICE_NAME_VI }}
  LEKTOR_SERVICE_NAME_WO: ${{ secrets.LEKTOR_SERVICE_NAME_WO }}
  LEKTOR_SERVICE_NAME_ZH_CN: ${{ secrets.LEKTOR_SERVICE_NAME_ZH_CN }}
  LEKTOR_SERVICE_NAME_ZH_TW: ${{ secrets.LEKTOR_SERVICE_NAME_ZH_TW }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    container:
      # Right now we're sticking to Python 3.8 due to dependency issues.
      image: python:3.13-bullseye

    concurrency:
      group: ci-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          set-safe-directory: true

      - name: Provision
        run: scripts/provision

      - name: Build
        run: scripts/build

      # The following tasks would add Onion Launchpad docs to all sites, but it's
      # currently disabled by the following reasons:
      #
      # 1. It increases build time.
      # 2. Currently Onion MkDocs is not shipped as a submodule, so
      #    it's build scripts aren't available.
      #
      #- name: Provision Docs
      #  run: vendors/onion-mkdocs/scripts/onion-mkdocs-provision-build
      #
      #- name: Docs
      #  run: vendors/onion-mkdocs/scripts/onion-mkdocs-build

      #
      # GitHub Action: Deploy to GitHub Pages
      # https://github.com/marketplace/actions/deploy-to-github-pages
      #
      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Disable Jekyll
        run: |
          touch public/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public

      #
      # GitHub Action: GitHub Pages action
      # https://github.com/marketplace/actions/github-pages-action
      #
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3
      #  # If you're changing the branch from main,
      #  # also change the `main` in `refs/heads/main`
      #  # below accordingly.
      #  if: ${{ github.ref == 'refs/heads/main' }}
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./build
